### ISSUE TITLE
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by reidjr2** [andyb2000/HACS-husqvarna_automower_ble#11]
Very excited by this awesome work by alistair23, and thank you for the integration.

I am getting the above when trying to add the integration. I am running HA as a docker container, and access is by https://[mydomainname]:8123 . A few googles suggest other integrations failing due to the url.  I am suspicious that is the cause of the problem, but any advise would be welcome.

**Comment by andyb2000** [comment]
Hi,
I believe this is resolved, I made an error in previous config_flow, please pull the latest #15 merge
