### ISSUE TITLE
Getting following error:  Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by Shiva2k5** [andyb2000/HACS-husqvarna_automower_ble#13]
Hi Andy, 

Thanks a lot for your project - appreciate the work by you and Alistair. 

When I add the Husquarna BLE integration - I get the following error. 

Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

Any ideas - how and why ? 

Regards,
Shivendra.

**Comment by andyb2000** [comment]
Hi,
I believe this is resolved, I made an error in previous config_flow, please pull the latest #15 merge
